### ISSUE TITLE
Krunker India Logo.gif

### ISSUE THREAD

**Issue by Jytesh** [krunker-india/krunker-india-website#4]
Can you make the gif play only on hover?
Twitter icon is missing

**Comment by Jytesh** [comment]
Add Twitch and Youtube icons too

**Comment by kevalpithadiya** [comment]
Yes I'll add the icons 👍🏽
Will have to do some gulugulu for gif but will do 👍🏽

**Comment by kevalpithadiya** [comment]
Done!
