### ISSUE TITLE
Mobile Site

### ISSUE THREAD

**Issue by Jytesh** [krunker-india/krunker-india-website#7]
The banner is squelched when used in Mobile

**Comment by kevalpithadiya** [comment]
Yes I will try to do something about it.

**Comment by kevalpithadiya** [comment]
Totally fixed it
![Hamsuke](https://camo.githubusercontent.com/4bf942853303032b7a3d644ab889050707990622/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3736353530393331333330393034383833322e676966)
